openapi: 3.0.1
info:
  title: test
  description: API Definition of test
  version: 1.0.0
servers:
- url: http://localhost:8290/tst
paths:
  /{name}/new:
    post:
      parameters:
      - name: name
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
